### ISSUE TITLE
Without Watermark broken for videos after July 26, 2020

### ISSUE THREAD

**Issue by davidteather** [TufayelLUS/TikTok-Video-Downloader-PHP#10]
TikTok changed a few things and the videos without watermarks are broken.

See [here](https://github.com/drawrowfly/tiktok-scraper/issues/266)

**Comment by dutchtom91** [comment]
It’s broken on all websites. It looks like TikTok changed the private API again. Maybe I can find the new url again. But I don’t know how to implant it.

**Comment by davidteather** [comment]
Yeah I'm trying to find a solution. Works on videos before july 27th

**Comment by TufayelLUS** [comment]
Yeah, the API is good, just new videos seem to have video ID missing from their video body which is causing this problem. This can only be fixed when there will be any new method to get the video ID for new videos. And yes, seems like videos older than 27th July are working properly.

**Comment by habibmy** [comment]
I am trying to download a vidoe published in March but still the downloaded video contains watermark. I tried same with https://snaptik.app/in and https://ssstiktok.io/ the both worked perfectly.

**Comment by TufayelLUS** [comment]
Hi @habibmy there are many videos that are re-uploaded in TikTok. So they might contain double layer of the watermark. If you are trying to get watermark free video from re-uploaded videos, those aren't going to help here. Because watermark-free API provides original video only. so, if original video already contains a watermark, it cannot be removed.

**Comment by TufayelLUS** [comment]
Looks like the API is gone dead again. It does produce video links, but unfortunately, that's not the watermark free video.

**Comment by TufayelLUS** [comment]
Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.

**Comment by tonyquang** [comment]
> Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.

Your code is still not working for new video uploaded after july 27th

**Comment by TufayelLUS** [comment]
> > Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.
> 
> Your code is still not working for new video uploaded after july 27th

I am already concerned about this issue. This is happening because of missing meta information for video id on new videos uploaded. And since there is no video id found, the api is remaining incomplete to be able to produce watermark free videos. As soon as I will figure out a solution for this, this issue will be marked as completed with an update on the code.

**Comment by habibmy** [comment]
> Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.

It is still the same. Gives video with watermark. The video is too old and it is downloading without with other sites .

**Comment by tonyquang** [comment]
> > > Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.
> > 
> > 
> > Your code is still not working for new video uploaded after july 27th
> 
> I am already concerned about this issue. This is happening because of missing meta information for video id on new videos uploaded. And since there is no video id found, the api is remaining incomplete to be able to produce watermark free videos. As soon as I will figure out a solution for this, this issue will be marked as completed with an update on the code.

Thank you ^^

**Comment by TufayelLUS** [comment]
> > Hi, @habibmy your problem is now fixed. You can try again. It was a slight parameter update on the API, without them, it does not work now.
> 
> It is still the same. Gives video with watermark. The video is too old and it is downloading without with other sites .

Would you mind sharing the video URL to me so that I can dig more about this issue?

**Comment by ssovit** [comment]
https://rapidapi.com/wppressapi-wppressapi-default/api/tiktok9 this API has endpoint that works with non watermarked videos.

**Comment by TufayelLUS** [comment]
@ssovit does it work with new videos too? Like videos from and after July 27th?

**Comment by davidteather** [comment]
@TufayelLUS yeah there's some on rapidapi that do work, but they're probably using mobile endpoints, which you need some different parameters to create. If you want to learn more [here's](https://github.com/davidteather/TikTok-Api/issues/120) an issue on my repo about it.
The one he's promoting is also his own rapidapi

**Comment by ssovit** [comment]
> @ssovit does it work with new videos too? Like videos from and after July 27th?

yeah.. I am promoting, I am giving off something for far cheaper than other API endpoints for tiktok in rapidapi, to the atleast to cover my droplets costs.. I would open up my code and say what I am using, but I am afraid they will get closed too..

**Comment by davidteather** [comment]
Yeah it makes sense, it probably would end up getting patched I imagine.

**Comment by ssovit** [comment]
> Yeah it makes sense, it probably would end up getting patched I imagine.

I hope it doesn't happen soon.

**Comment by sarabhi92git** [comment]
Still getting blank url in without watermark video link

**Comment by TufayelLUS** [comment]
Hi @sarabhi92git ,
It is clearly stated in the server page and in the comments of this issue page that videos before July 27, 2020 works without any trouble and videos from and after July 27, 2020, no longer contains any metadata for video key and hence this traditional way doesn't work for those videos.
I am still looking for a suitable and easy to use solution for this but not going to use any 3rd party APIs for that. As soon as there's an update, you will see this issue marked as closed and update in the repository code.
Thank you very much.

**Comment by tonyquang** [comment]
> Hi @sarabhi92git ,
> It is clearly stated in the server page and in the comments of this issue page that videos before July 27, 2020 works without any trouble and videos from and after July 27, 2020, no longer contains any metadata for video key and hence this traditional way doesn't work for those videos.
> I am still looking for a suitable and easy to use solution for this but not going to use any 3rd party APIs for that. As soon as there's an update, you will see this issue marked as closed and update in the repository code.
> Thank you very much.

Thanks a lot bro ^^

**Comment by sarabhi92git** [comment]
> Hi @sarabhi92git ,
> It is clearly stated in the server page and in the comments of this issue page that videos before July 27, 2020 works without any trouble and videos from and after July 27, 2020, no longer contains any metadata for video key and hence this traditional way doesn't work for those videos.
> I am still looking for a suitable and easy to use solution for this but not going to use any 3rd party APIs for that. As soon as there's an update, you will see this issue marked as closed and update in the repository code.
> Thank you very much.

Thank you, Friend 👍

**Comment by aftabaminzoobiapps** [comment]
can you give me this code in javascript? I am working for 12 days. but didn't do this.

**Comment by TufayelLUS** [comment]
> can you give me this code in javascript? I am working for 12 days. but didn't do this.

It may not work with javascript only because TikTok looks for HTTP referer, cookies, and you may face CORS policy issues too(I am not sure anyway.)

**Comment by aftabaminzoobiapps** [comment]
> > can you give me this code in javascript? I am working for 12 days. but didn't do this.
> 
> It may not work with javascript only because TikTok looks for HTTP referer, cookies, and you may face CORS policy issues too(I am not sure anyway.)

I have done it. thanks, bro.

**Comment by TufayelLUS** [comment]
Wow, congrats. Enjoy.

**Comment by TufayelLUS** [comment]
> > > can you give me this code in javascript? I am working for 12 days. but didn't do this.
> > 
> > 
> > It may not work with javascript only because TikTok looks for HTTP referer, cookies, and you may face CORS policy issues too(I am not sure anyway.)
> 
> I have done it. thanks, bro.

Congrats, enjoy.

**Comment by Kucklovod00** [comment]
guys share the solution please
